runtime: php
env: flex

runtime_config:
  document_root: public

skip_files: 
  - .env

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:e5iAbhAg6oYYIYnw+35gG4SP00E96Rku1+uPugryY9E=
  APP_ENV: local
  APP_DEBUG: true
  # APP_STORAGE: /tmp
  # VIEW_COMPILED_PATH: /tmp

  SESSION_DRIVER: file
  CACHE_DRIVER: file

  APP_LOG: daily
  APP_TIMEZONE: UTC #your timezone of choice
  
  # follow the part of the tutorial on setting up your SQL database
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: catalogo_proyecto
  DB_USERNAME: root
  DB_PASSWORD: 159753..
  DB_SOCKET: "/cloudsql/cotizaciones-322416:southamerica-east1:cotizaciones"
  # QUEUE_DRIVER: database #in case you execute queued jobs

  # MAIL_DRIVER: smtp
  # MAIL_HOST: smtp.sparkpostmail.com
  # MAIL_PORT: 587
  # MAIL_USERNAME: sparkpost_username
  # MAIL_PASSWORD: ****************

  LOG_DELETE:  true # this is a parameter added by us in the project .env file. You can add here any setting you would add to your .env file
  # GOOGLE_VISION_PROJECT_ID: project_id
  #we need this for the flex environment
beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "cotizaciones-322416:southamerica-east1:cotizaciones"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2